package:
  name: medaka
  version: 2.0.1

source:
  path: ../  # adjust this to where your custom medaka source is

build:
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python
    - pip

  host:
    - python =3.11
    - pip
    - setuptools

  run:
    - python =3.11
    - bcftools =1.21
    - python_abi =3.11
    - brotli-python =1.1.0
    - cached-property =1.5.2
    - cffi =1.17.1
    - charset-normalizer =3.4.1
    - colorama
    - filelock
    - fsspec
    - gmpy2 =2.2.1
    - grpcio =1.62.2
    - gsl =2.7
    - h5py =3.13.0
    - hdf5 =1.14.3
    - idna =3.10
    - intervaltree
    - jinja2
    - k8 =0.2.5
    - mappy =2.28
    - minimap2 =2.28
    - numpy =1.26.4
    - ont-fast5-api =4.1.3
    - packaging
    - parasail-python =1.3.4
    - pyabpoa =1.5.3
    - pycparser
    - pysam =0.22.1
    - pysocks
    - pyspoa =0.2.1
    - python-edlib =1.3.9.post1
    - pytorch =2.3.1
    - requests
    - samtools =1.21
    - sortedcontainers
    - sympy
    - tqdm
    - typing_extensions
    - zstandard

test:
  imports:
    - medaka
  commands:
    - medaka --help

about:
  home: https://github.com/ethan-mcq/medaka
  license: none
  license_file: LICENSE
  summary: Custom version of Medaka for ONT polishing.

extra:
  recipe-maintainers:
    - ethan-mcq
